### ISSUE TITLE
Widevine Key + Key ID - Missing Channels

### ISSUE THREAD

**Issue by gambitx20** [samleong123/mewatchsg#2]
Hi there, 

eGG Network is missing from the playlist.
Are you able to check and add?

Also I think oktoholidays is no longer working, i think it has already been decomissioned.

Thank you for making this playlist available!

**Comment by samleong123** [comment]
the Widevine Key + Key ID is no longer maintained because Google patched a new Widevine CDM so i can't get the new Key + Key ID 

the only way is to use the Widevine URL which includes Beijing 2022 channels , note that the Widevine URL will be updated every day so be sure to update the playlist everyday
