### ISSUE TITLE
Channel issues

### ISSUE THREAD

**Issue by ctmaqil** [samleong123/mewatchsg#9]
Channel 5 
Suria
Vasantham 

[mewatchsg_drm_wv_key.m3u8](https://github.com/samleong123/mewatchsg/blob/main/mewatchsg_drm_wv_key.m3u8) Issues

**Comment by samleong123** [comment]
Widevine key version will not be maintained anymore because the exploit has been fixed by Google
Please refer to Part [Widevine Key + Key ID](https://mewatchsg.samsam123.name.my/mewatchsg_drm_wv_key.m3u8) under the readme of this [repo](https://github.com/samleong123/mewatchsg#before-you-use-this-playlist)

Solution : use Widevine URL version
